input_data_path: "data/raw/heart_cleveland_upload.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"
downloading_params:
  s3_bucket: for-dvc
  paths:
    - train.csv
    - test.csv
  output_folder: "data/raw/"
splitting_params:
  val_size: 0.5
  random_state: 42
train_params:
  model_type: "RandomForestClassifier"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  features_to_drop:
    - "fbs"
    - "restecg"
  target_col: "condition"
  