apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-ml-pod-liveness-rolling-update
  labels:
    app: fastapi-ml-pod-liveness-rolling-update
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: fastapi-ml-pod-liveness-rolling-update
  template:
    metadata:
      name: fastapi-ml-pod-liveness-rolling-update
      labels:
        app: fastapi-ml-pod-liveness-rolling-update
    spec:
      containers:
        - image: dan1ar/ml_prod_hw2
          name: fastapi-ml-pod-liveness-rolling-update
          ports:
            - containerPort: 5000