apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-ml-pod-liveness-blue-green
  labels:
    app: fastapi-ml-pod-liveness-blue-green
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 6
      maxUnavailable: 0
  selector:
    matchLabels:
      app: fastapi-ml-pod-liveness-blue-green
  template:
    metadata:
      name: fastapi-ml-pod-liveness-blue-green
      labels:
        app: fastapi-ml-pod-liveness-blue-green
    spec:
      containers:
        - image: dan1ar/ml_prod_hw2
          name: fastapi-ml-pod-liveness-blue-green
          ports:
            - containerPort: 5000