apiVersion: v1
kind: Pod
metadata:
  name: fastapi-ml-pod-resources
  labels:
    app: fastapi-ml-pod-resources
spec:
  containers:
    - name: fastapi-ml
      image: dan1ar/ml_prod_hw2:latest
      ports:
        - name: api
          containerPort: 5000

      resources:
        requests:
          memory: "64Mi"
          cpu: "0.5"
        limits:
          memory: "256Mi"
          cpu: "1"